In [1]:
import pandas as pd

In [2]:
percentile = pd.read_csv("percentileCENSUSdata.csv")
population = pd.read_csv("cleanedCENSUSdata.csv")

In [3]:
ethnicity_perc = percentile[['STNAME','CTYNAME', 'TOT_POP','NHWA_MALE','NHWA_FEMALE','NHBA_MALE','NHBA_FEMALE','NHIA_MALE','NHIA_FEMALE','NHAA_MALE','NHAA_FEMALE','NHNA_MALE','NHNA_FEMALE','H_MALE','H_FEMALE']]

In [4]:
ethnicity_perc.head()

,STNAME,CTYNAME,TOT_POP,NHWA_MALE,NHWA_FEMALE,NHBA_MALE,NHBA_FEMALE,NHIA_MALE,NHIA_FEMALE,NHAA_MALE,NHAA_FEMALE,NHNA_MALE,NHNA_FEMALE,H_MALE,H_FEMALE
0,Alabama,Autauga County,100.0,36.045034,37.725751,9.255580,10.608745,0.187940,0.247006,0.504752,0.651524,0.035798,0.035798,1.582273,1.408652
1,Alabama,Baldwin County,100.0,40.247005,42.960302,4.169616,4.437944,0.337314,0.337762,0.408092,0.642823,0.023742,0.031357,2.483941,2.234875
2,Alabama,Barbour County,100.0,23.875881,21.635745,25.358503,22.470226,0.210646,0.174188,0.222798,0.247104,0.085068,0.040509,2.548003,1.976829
3,Alabama,Bibb County,100.0,37.876217,36.532107,13.003483,8.069126,0.223274,0.183085,0.093775,0.111637,0.022327,0.004465,1.531660,1.250335
4,Alabama,Blount County,100.0,42.358109,44.412548,0.783385,0.724588,0.247294,0.240376,0.126241,0.155639,0.024211,0.012105,5.101511,4.551586

In [5]:
ethnicity = population[['STNAME','CTYNAME', 'TOT_POP','NHWA_MALE','NHWA_FEMALE','NHBA_MALE','NHBA_FEMALE','NHIA_MALE','NHIA_FEMALE','NHAA_MALE','NHAA_FEMALE','NHNA_MALE','NHNA_FEMALE','H_MALE','H_FEMALE']]

In [6]:
ethnicity.head()

,STNAME,CTYNAME,TOT_POP,NHWA_MALE,NHWA_FEMALE,NHBA_MALE,NHBA_FEMALE,NHIA_MALE,NHIA_FEMALE,NHAA_MALE,NHAA_FEMALE,NHNA_MALE,NHNA_FEMALE,H_MALE,H_FEMALE
0,Alabama,Autauga County,55869,20138,21077,5171,5927,105,138,282,364,20,20,884,787
1,Alabama,Baldwin County,223234,89845,95902,9308,9907,753,754,911,1435,53,70,5545,4989
2,Alabama,Barbour County,24686,5894,5341,6260,5547,52,43,55,61,21,10,629,488
3,Alabama,Bibb County,22394,8482,8181,2912,1807,50,41,21,25,5,1,343,280
4,Alabama,Blount County,57826,24494,25682,453,419,143,139,73,90,14,7,2950,2632

In [7]:
sum_column = ethnicity_perc['NHWA_MALE']+ ethnicity_perc['NHWA_FEMALE']
ethnicity_perc['NHWA_perc'] = sum_column

sum_column = ethnicity_perc['NHBA_MALE']+ ethnicity_perc['NHBA_FEMALE']
ethnicity_perc['NHBA_perc'] = sum_column

sum_column = ethnicity_perc['NHIA_MALE']+ ethnicity_perc['NHIA_FEMALE']
ethnicity_perc['NHIA_perc'] = sum_column

sum_column = ethnicity_perc['NHAA_MALE']+ ethnicity_perc['NHAA_FEMALE']
ethnicity_perc['NHAA_perc'] = sum_column

sum_column = ethnicity_perc['NHNA_MALE']+ ethnicity_perc['NHNA_FEMALE']
ethnicity_perc['NHNA_perc'] = sum_column

sum_column = ethnicity_perc['H_MALE']+ ethnicity_perc['H_FEMALE']
ethnicity_perc['H_perc'] = sum_column

ethnicity_perc = ethnicity_perc[['STNAME','CTYNAME', 'NHWA_perc', 'NHBA_perc','NHIA_perc','NHAA_perc','NHNA_perc','H_perc']]
ethnicity_perc.head()

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,STNAME,CTYNAME,NHWA_perc,NHBA_perc,NHIA_perc,NHAA_perc,NHNA_perc,H_perc
0,Alabama,Autauga County,73.770785,19.864325,0.434946,1.156276,0.071596,2.990925
1,Alabama,Baldwin County,83.207307,8.607560,0.675076,1.050915,0.055099,4.718815
2,Alabama,Barbour County,45.511626,47.828729,0.384834,0.469902,0.125577,4.524832
3,Alabama,Bibb County,74.408324,21.072609,0.406359,0.205412,0.026793,2.781995
4,Alabama,Blount County,86.770657,1.507972,0.487670,0.281880,0.036316,9.653097

In [8]:
sum_column = ethnicity['NHWA_MALE']+ ethnicity['NHWA_FEMALE']
ethnicity['NHWA'] = sum_column

sum_column = ethnicity['NHBA_MALE']+ ethnicity['NHBA_FEMALE']
ethnicity['NHBA'] = sum_column

sum_column = ethnicity['NHIA_MALE']+ ethnicity['NHIA_FEMALE']
ethnicity['NHIA'] = sum_column

sum_column = ethnicity['NHAA_MALE']+ ethnicity['NHAA_FEMALE']
ethnicity['NHAA'] = sum_column

sum_column = ethnicity['NHNA_MALE']+ ethnicity['NHNA_FEMALE']
ethnicity['NHNA'] = sum_column

sum_column = ethnicity['H_MALE']+ ethnicity['H_FEMALE']
ethnicity['H'] = sum_column

ethnicity = ethnicity[['STNAME','CTYNAME', 'NHWA', 'NHBA','NHIA','NHAA','NHNA','H']]
ethnicity.head()

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    STNAME         CTYNAME    NHWA   NHBA  NHIA  NHAA  NHNA      H
0  Alabama  Autauga County   41215  11098   243   646    40   1671
1  Alabama  Baldwin County  185747  19215  1507  2346   123  10534
2  Alabama  Barbour County   11235  11807    95   116    31   1117
3  Alabama     Bibb County   16663   4719    91    46     6    623
4  Alabama   Blount County   50176    872   282   163    21   5582

In [11]:
ethniccensus = ethnicity.merge(ethnicity_perc)

In [12]:
ethniccensus.head()

,STNAME,CTYNAME,NHWA,NHBA,NHIA,NHAA,NHNA,H,NHWA_perc,NHBA_perc,NHIA_perc,NHAA_perc,NHNA_perc,H_perc
0,Alabama,Autauga County,41215,11098,243,646,40,1671,73.770785,19.864325,0.434946,1.156276,0.071596,2.990925
1,Alabama,Baldwin County,185747,19215,1507,2346,123,10534,83.207307,8.607560,0.675076,1.050915,0.055099,4.718815
2,Alabama,Barbour County,11235,11807,95,116,31,1117,45.511626,47.828729,0.384834,0.469902,0.125577,4.524832
3,Alabama,Bibb County,16663,4719,91,46,6,623,74.408324,21.072609,0.406359,0.205412,0.026793,2.781995
4,Alabama,Blount County,50176,872,282,163,21,5582,86.770657,1.507972,0.487670,0.281880,0.036316,9.653097

In [14]:
ethniccensus.to_csv (r'C:\Users\javie\Desktop\CENSUSbyETHNICITY.csv', index = False, header=True)