In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
EIA = pd.read_csv("cleanedEIAdata.csv")
percentile = pd.read_csv("percentileCENSUSdata.csv")
population = pd.read_csv("cleanedCENSUSdata.csv")

In [4]:
percentile.head()

,STNAME,CTYNAME,TOT_POP,TOT_MALE,TOT_FEMALE,WA_MALE,WA_FEMALE,BA_MALE,BA_FEMALE,IA_MALE,...,HWAC_MALE,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE
0,Alabama,Autauga County,100.0,48.492008,51.507992,37.369561,38.892767,9.373714,10.739408,0.216578,...,1.392543,1.229662,0.159301,0.166461,0.071596,0.048327,0.026849,0.034008,0.028638,0.019689
1,Alabama,Baldwin County,100.0,48.490373,51.509627,42.471129,44.969852,4.249353,4.527536,0.404508,...,2.304308,2.081224,0.120053,0.125877,0.118262,0.088248,0.030909,0.029117,0.024638,0.015679
2,Alabama,Barbour County,100.0,52.920684,47.079316,25.881066,23.272300,25.565098,22.664668,0.417241,...,2.061897,1.652759,0.255205,0.202544,0.247104,0.105323,0.004051,0.000000,0.056712,0.032407
3,Alabama,Bibb County,100.0,53.268733,46.731267,39.144414,37.621684,13.132982,8.136108,0.236671,...,1.299455,1.129767,0.142895,0.084844,0.026793,0.066982,0.022327,0.004465,0.075913,0.013396
4,Alabama,Blount County,100.0,49.237367,50.762633,47.137966,48.687442,0.892332,0.798949,0.332031,...,4.831737,4.350984,0.131429,0.100301,0.115865,0.114136,0.031128,0.036316,0.058797,0.036316

In [11]:
WhiteVPOC_percentile = percentile[['STNAME','CTYNAME', 'TOT_POP','WA_MALE','WA_FEMALE']]
WhiteVPOC_total = population[['STNAME','CTYNAME', 'TOT_POP','WA_MALE','WA_FEMALE']]

In [23]:
sum_column = WhiteVPOC_percentile['WA_MALE']+ WhiteVPOC_percentile['WA_FEMALE']
WhiteVPOC_percentile['WA'] = sum_column

sum_column = WhiteVPOC_percentile['TOT_POP'] - WhiteVPOC_percentile['WA']
WhiteVPOC_percentile['POC'] = sum_column

WhiteVPOC_percentile = WhiteVPOC_percentile[['STNAME','CTYNAME', 'TOT_POP', 'WA','POC']]
WhiteVPOC_percentile.head()

    STNAME         CTYNAME  TOT_POP         WA        POC
0  Alabama  Autauga County    100.0  76.262328  23.737672
1  Alabama  Baldwin County    100.0  87.440981  12.559019
2  Alabama  Barbour County    100.0  49.153366  50.846634
3  Alabama     Bibb County    100.0  76.766098  23.233902
4  Alabama   Blount County    100.0  95.825407   4.174593

In [24]:
sum_column = WhiteVPOC_total['WA_MALE']+ WhiteVPOC_total['WA_FEMALE']
WhiteVPOC_total['WA'] = sum_column

sum_column = WhiteVPOC_total['TOT_POP'] - WhiteVPOC_total['WA']
WhiteVPOC_total['POC'] = sum_column

WhiteVPOC_total = WhiteVPOC_total[['STNAME','CTYNAME', 'TOT_POP', 'WA','POC']]
WhiteVPOC_total.head()

    STNAME         CTYNAME  TOT_POP      WA    POC
0  Alabama  Autauga County    55869   42607  13262
1  Alabama  Baldwin County   223234  195198  28036
2  Alabama  Barbour County    24686   12134  12552
3  Alabama     Bibb County    22394   17191   5203
4  Alabama   Blount County    57826   55412   2414

In [3]:
WhiteVBlackVHispanic_percentile = percentile[['STNAME','CTYNAME', 'TOT_POP','NHWA_MALE','NHWA_FEMALE','NHBA_MALE','NHBA_FEMALE', 'H_MALE','H_FEMALE']]
WhiteVBlackVHispanic_total = population[['STNAME','CTYNAME', 'TOT_POP','NHWA_MALE','NHWA_FEMALE','NHBA_MALE','NHBA_FEMALE', 'H_MALE','H_FEMALE']]
WhiteVBlackVHispanic_percentile.head()

,STNAME,CTYNAME,TOT_POP,NHWA_MALE,NHWA_FEMALE,NHBA_MALE,NHBA_FEMALE,H_MALE,H_FEMALE
0,Alabama,Autauga County,100.0,36.045034,37.725751,9.255580,10.608745,1.582273,1.408652
1,Alabama,Baldwin County,100.0,40.247005,42.960302,4.169616,4.437944,2.483941,2.234875
2,Alabama,Barbour County,100.0,23.875881,21.635745,25.358503,22.470226,2.548003,1.976829
3,Alabama,Bibb County,100.0,37.876217,36.532107,13.003483,8.069126,1.531660,1.250335
4,Alabama,Blount County,100.0,42.358109,44.412548,0.783385,0.724588,5.101511,4.551586

In [4]:
sum_column = WhiteVBlackVHispanic_percentile['NHWA_MALE']+ WhiteVBlackVHispanic_percentile['NHWA_FEMALE']
WhiteVBlackVHispanic_percentile['NHWA'] = sum_column

sum_column = WhiteVBlackVHispanic_percentile['NHBA_MALE']+ WhiteVBlackVHispanic_percentile['NHBA_FEMALE']
WhiteVBlackVHispanic_percentile['NHBA'] = sum_column

sum_column = WhiteVBlackVHispanic_percentile['H_MALE']+ WhiteVBlackVHispanic_percentile['H_FEMALE']
WhiteVBlackVHispanic_percentile['H'] = sum_column

WhiteVBlackVHispanic_percentile = WhiteVBlackVHispanic_percentile[['STNAME','CTYNAME', 'TOT_POP', 'NHWA','NHBA','H']]
WhiteVBlackVHispanic_percentile.head()

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    STNAME         CTYNAME  TOT_POP       NHWA       NHBA         H
0  Alabama  Autauga County    100.0  73.770785  19.864325  2.990925
1  Alabama  Baldwin County    100.0  83.207307   8.607560  4.718815
2  Alabama  Barbour County    100.0  45.511626  47.828729  4.524832
3  Alabama     Bibb County    100.0  74.408324  21.072609  2.781995
4  Alabama   Blount County    100.0  86.770657   1.507972  9.653097

In [5]:
sum_column = WhiteVBlackVHispanic_total['NHWA_MALE']+ WhiteVBlackVHispanic_total['NHWA_FEMALE']
WhiteVBlackVHispanic_total['NHWA'] = sum_column

sum_column = WhiteVBlackVHispanic_total['NHBA_MALE']+ WhiteVBlackVHispanic_total['NHBA_FEMALE']
WhiteVBlackVHispanic_total['NHBA'] = sum_column

sum_column = WhiteVBlackVHispanic_total['H_MALE']+ WhiteVBlackVHispanic_total['H_FEMALE']
WhiteVBlackVHispanic_total['H'] = sum_column

WhiteVBlackVHispanic_total = WhiteVBlackVHispanic_total[['STNAME','CTYNAME', 'TOT_POP', 'NHWA','NHBA','H']]
WhiteVBlackVHispanic_total.head()

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    STNAME         CTYNAME  TOT_POP    NHWA   NHBA      H
0  Alabama  Autauga County    55869   41215  11098   1671
1  Alabama  Baldwin County   223234  185747  19215  10534
2  Alabama  Barbour County    24686   11235  11807   1117
3  Alabama     Bibb County    22394   16663   4719    623
4  Alabama   Blount County    57826   50176    872   5582

In [40]:
WhiteHispanicVPOC_percentile = percentile[['STNAME','CTYNAME', 'TOT_POP','NHWA_MALE','NHWA_FEMALE','H_MALE','H_FEMALE']]
WhiteHispanicVPOC_total = population[['STNAME','CTYNAME', 'TOT_POP','NHWA_MALE','NHWA_FEMALE','H_MALE','H_FEMALE']]
WhiteHispanicVPOC_percentile.head()

,STNAME,CTYNAME,TOT_POP,NHWA_MALE,NHWA_FEMALE,H_MALE,H_FEMALE
0,Alabama,Autauga County,100.0,36.045034,37.725751,1.582273,1.408652
1,Alabama,Baldwin County,100.0,40.247005,42.960302,2.483941,2.234875
2,Alabama,Barbour County,100.0,23.875881,21.635745,2.548003,1.976829
3,Alabama,Bibb County,100.0,37.876217,36.532107,1.531660,1.250335
4,Alabama,Blount County,100.0,42.358109,44.412548,5.101511,4.551586

In [41]:
sum_column = WhiteHispanicVPOC_percentile['NHWA_MALE']+ WhiteHispanicVPOC_percentile['NHWA_FEMALE']+ WhiteHispanicVPOC_percentile['H_MALE']+WhiteHispanicVPOC_percentile['H_FEMALE']
WhiteHispanicVPOC_percentile['HISPANIC OR WHITE'] = sum_column

sum_column = WhiteHispanicVPOC_percentile['TOT_POP'] - WhiteHispanicVPOC_percentile['HISPANIC OR WHITE']
WhiteHispanicVPOC_percentile['POC'] = sum_column

WhiteHispanicVPOC_percentile = WhiteHispanicVPOC_percentile[['STNAME','CTYNAME', 'TOT_POP', 'HISPANIC OR WHITE','POC']]
WhiteHispanicVPOC_percentile.head()

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

    STNAME         CTYNAME  TOT_POP  HISPANIC OR WHITE        POC
0  Alabama  Autauga County    100.0          76.761710  23.238290
1  Alabama  Baldwin County    100.0          87.926122  12.073878
2  Alabama  Barbour County    100.0          50.036458  49.963542
3  Alabama     Bibb County    100.0          77.190319  22.809681
4  Alabama   Blount County    100.0          96.423754   3.576246

In [42]:
sum_column = WhiteHispanicVPOC_total['NHWA_MALE']+ WhiteHispanicVPOC_total['NHWA_FEMALE']+ WhiteHispanicVPOC_total['H_MALE']+WhiteHispanicVPOC_total['H_FEMALE']
WhiteHispanicVPOC_total['HISPANIC OR WHITE'] = sum_column

sum_column = WhiteHispanicVPOC_total['TOT_POP'] - WhiteHispanicVPOC_total['HISPANIC OR WHITE']
WhiteHispanicVPOC_total['POC'] = sum_column

WhiteHispanicVPOC_total = WhiteHispanicVPOC_total[['STNAME','CTYNAME', 'TOT_POP', 'HISPANIC OR WHITE','POC']]
WhiteHispanicVPOC_total.head()

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

    STNAME         CTYNAME  TOT_POP  HISPANIC OR WHITE    POC
0  Alabama  Autauga County    55869              42886  12983
1  Alabama  Baldwin County   223234             196281  26953
2  Alabama  Barbour County    24686              12352  12334
3  Alabama     Bibb County    22394              17286   5108
4  Alabama   Blount County    57826              55758   2068

In [43]:
WhiteVPOC_percentile.to_csv (r'C:\Users\javie\Desktop\WHITEVPOC_percentile.csv', index = False, header=True)
WhiteVPOC_total.to_csv (r'C:\Users\javie\Desktop\WHITEVPOC_total.csv', index = False, header=True)
WhiteVBlackVHispanic_percentile.to_csv (r'C:\Users\javie\Desktop\WHITEVBLACKVHISPANIC_percentile.csv', index = False, header=True)
WhiteVBlackVHispanic_total.to_csv (r'C:\Users\javie\Desktop\WHITEVBLACKVHISPANIC_total.csv', index = False, header=True)
WhiteHispanicVPOC_percentile.to_csv (r'C:\Users\javie\Desktop\WHITEHISPANICVPOC_percentile.csv', index = False, header=True)
WhiteHispanicVPOC_total.to_csv (r'C:\Users\javie\Desktop\WHITEHISPANICVPOC_total.csv', index = False, header=True)

In [6]:
WhiteVBlackVHispanic_percentile.to_csv (r'C:\Users\javie\Desktop\WHITEVBLACKVHISPANIC_percentile.csv', index = False, header=True)
WhiteVBlackVHispanic_total.to_csv (r'C:\Users\javie\Desktop\WHITEVBLACKVHISPANIC_total.csv', index = False, header=True)